Portfolio
xaleehrtyunus/portfolio pull request #1
Opened 2021-08-12 14:49 UTC by xaleehrtyunus

## portfolio
In this project;
 I created a mobile version of my portfolio 
- I added icons
- I added text

2021-08-12 17:50 UTC, tahiry-dev requested changes
Hello xaleehrtyunus👋

You did a great job but there are few issues you need to update before moving to the next project

I appreciate your effort to implement bootstrap in your project 🙏, but for this section, and for this project here are the general requirements:

- Understand how to parse a Figma design to create a UI.
- Use Flexbox to place elements on the page.
- Use images and backgrounds to enhance the look of the website.

Consequently, using bootstrap might prevent you to fulfill those requirements, so I suggest you using HTML-CSS only

## Required Changes ♻️

_Kindly check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-12 17:50 UTC, tahiry-dev commented on README.md
> +![screenshot](./app_screenshot.png)
- Your screenshot couldn't be shown, would you please fix it?

2021-08-12 17:50 UTC, tahiry-dev commented on README.md
> +
- It is better to inform your visitor how to run your project locally

2021-08-12 17:50 UTC, tahiry-dev commented on css/styles.css
>  }
- For this project, we need to use Flexbox to align element please

2021-08-12 17:50 UTC, tahiry-dev commented on index.html
> +			<img class="icons" src="./images/smallcycle.png" alt="circle">
-Those images are there for decoration. I think it is better to use them as a background image.

2021-08-14 10:38 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

## Hi Zaliha Gambo Yunusa, 
### Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
### OPTIONAL BUT RECOMMENDED
- [ ] Please see inline comments.
## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-14 10:38 UTC, SajjadAhmad14 commented on index.html
> +			<a class="logo" href="#">My logo</a>
[OPTIONAL] Please follow the exact font and color defined in the design.

2021-08-14 10:38 UTC, SajjadAhmad14 commented on index.html
> +				<p>I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hes
[OPTIONAL] Please follow the exact font and color defined in the design.

2021-08-14 10:38 UTC, SajjadAhmad14 commented on index.html
> +			<a href="#" class="connect">LET'S CONNECT</a>
[OPTIONAL] Please follow the exact font and color defined in the design.

2021-08-14 10:38 UTC, SajjadAhmad14 commented on index.html
> +		<header class="nav">
[OPTIONAL] Header on the web page has a large margin from the top. Please remove it.

2021-08-14 11:14 UTC, merged